# Generated by Django 6.0.2 on 2026-03-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
