upstream carpooling {
    server web:8000;
}

server {
    listen 80;
    server_name suryanshdvmtask.tech www.suryanshdvmtask.tech;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name suryanshdvmtask.tech www.suryanshdvmtask.tech;

    ssl_certificate /etc/letsencrypt/live/suryanshdvmtask.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/suryanshdvmtask.tech/privkey.pem;

    location / {
        proxy_pass http://carpooling;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /home/app/web/staticfiles/;
    }
}