# Generated by Django 6.0.2 on 2026-03-17 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('base_fee', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fare Configuration',
            },
        ),
        migrations.CreateModel(
            name='CarpoolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dropoff_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_requests', to='network.node')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_requests', to=settings.AUTH_USER_MODEL)),
                ('pickup_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to='network.node')),
                ('proximity_nodes', models.ManyToManyField(blank=True, related_name='proximity_requests', to='network.node')),
            ],
        ),
        migrations.CreateModel(
            name='CarpoolOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detour_length', models.PositiveIntegerField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_offers', to='trips.trip')),
                ('carpool_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='carpool.carpoolrequest')),
            ],
            options={
                'unique_together': {('trip', 'carpool_request')},
            },
        ),
    ]
